blueprint:
  name: Robb smarrt 8-button switch
  description: 'This blueprint is for the  Robb smarrt 8-button switch panel (ROBB
    ROB_200-007-0) when used with zha. (Should now also work for these types 
    ROB_200_025_0,VES-ZB-WAL-012,SR-ZG9001K8-DIM)

    It is for general use so all buttons can be connected to any action of your choice.
    This remote supports short button clicks and long button presses (over 4 seconds)

    Make sure to select the correct sensor for the remote.

    '
  domain: automation
  author: Bart Eversdijk
  source_url: https://github.com/Bekkie/ha-blueprints/blob/main/automation/robb-smart-8-switch-ROB_200-007-0.yaml
  input:
    remote:
      name: Remote
      description: Switch remote to use
      selector:
        device:
          filter:
            - integration: zha
              model: ROB_200-007-0
            - integration: zha
              model: ROB_200-025-0
            - integration: zha
              model: VES-ZB-WAL-012
            - integration: zha
              model: SR-ZG9001K8-DIM
            - integration: zha
              model: ED-10015
          multiple: false
    on_button_1_short:
      name: On button 1 - short
      default: []
      selector:
        action: {}
    off_button_1_short:
      name: Off button 1 - short
      default: []
      selector:
        action: {}
    on_button_1_long:
      name: On button 1 - long press
      default: []
      selector:
        action: {}
    off_button_1_long:
      name: Off button 1 - long press
      default: []
      selector:
        action: {}
    on_button_2_short:
      name: On button 2 - short
      default: []
      selector:
        action: {}
    off_button_2_short:
      name: Off button 2 - short
      default: []
      selector:
        action: {}
    on_button_2_long:
      name: On button 2 - long press
      default: []
      selector:
        action: {}
    off_button_2_long:
      name: Off button 2 - long press
      default: []
      selector:
        action: {}
    on_button_3_short:
      name: On button 3 - short
      default: []
      selector:
        action: {}
    off_button_3_short:
      name: Off button 3 - short
      default: []
      selector:
        action: {}
    on_button_3_long:
      name: On button 3 - long press
      default: []
      selector:
        action: {}
    off_button_3_long:
      name: Off button 3 - long press
      default: []
      selector:
        action: {}
    on_button_4_short:
      name: On button 4 - short
      default: []
      selector:
        action: {}
    off_button_4_short:
      name: Off button 4 - short
      default: []
      selector:
        action: {}
    on_button_4_long:
      name: On button 4 - long press
      default: []
      selector:
        action: {}
    off_button_4_long:
      name: Off button 4 - long press
      default: []
      selector:
        action: {}
mode: restart
max_exceeded: silent
trigger:
- platform: event
  event_type: zha_event
  event_data:
    device_id: !input remote
action:
- variables:
    button: '{{ trigger.event.data.endpoint_id }}'
    cmd: '{{ trigger.event.data.command }}'
- choose:
  - conditions:
    - '{{ button == 1 and cmd == "on" }}'
    sequence: !input on_button_1_short
  - conditions:
    - '{{ button == 1 and cmd == "off" }}'
    sequence: !input off_button_1_short
  - conditions:
    - '{{ button == 1 and cmd == "move_with_on_off" }}'
    sequence:
    - variables:
        mode: '{{ trigger.event.data.params.move_mode }}'
    - if:
      - condition:
        - '{{ mode == "MoveMode.Up" }}'
      then: !input on_button_1_long
  - conditions:
    - '{{ button == 1 and cmd == "move" }}'
    sequence:
    - variables:
        mode: '{{ trigger.event.data.params.move_mode }}'
    - if:
      - condition:
        - '{{ mode == "MoveMode.Down" }}'
      then: !input off_button_1_long
  - conditions:
    - '{{ button == 2 and cmd == "on" }}'
    sequence: !input on_button_2_short
  - conditions:
    - '{{ button == 2 and cmd == "off" }}'
    sequence: !input off_button_2_short
  - conditions:
    - '{{ button == 2 and cmd == "move_with_on_off" }}'
    sequence:
    - variables:
        mode: '{{ trigger.event.data.params.move_mode }}'
    - if:
      - condition:
        - '{{ mode == "MoveMode.Up" }}'
      then: !input on_button_2_long
  - conditions:
    - '{{ button == 2 and cmd == "move" }}'
    sequence:
    - variables:
        mode: '{{ trigger.event.data.params.move_mode }}'
    - if:
      - condition:
        - '{{ mode == "MoveMode.Down" }}'
      then: !input off_button_2_long
  - conditions:
    - '{{ button == 3 and cmd == "on" }}'
    sequence: !input on_button_3_short
  - conditions:
    - '{{ button == 3 and cmd == "off" }}'
    sequence: !input off_button_3_short
  - conditions:
    - '{{ button == 3 and cmd == "move_with_on_off" }}'
    sequence:
    - variables:
        mode: '{{ trigger.event.data.params.move_mode }}'
    - if:
      - condition:
        - '{{ mode == "MoveMode.Up" }}'
      then: !input on_button_3_long
  - conditions:
    - '{{ button == 3 and cmd == "move" }}'
    sequence:
    - variables:
        mode: '{{ trigger.event.data.params.move_mode }}'
    - if:
      - condition:
        - '{{ mode == "MoveMode.Down" }}'
      then: !input off_button_3_long
  - conditions:
    - '{{ button == 4 and cmd == "on" }}'
    sequence: !input on_button_4_short
  - conditions:
    - '{{ button == 4 and cmd == "off" }}'
    sequence: !input off_button_4_short
  - conditions:
    - '{{ button == 4 and cmd == "move_with_on_off" }}'
    sequence:
    - variables:
        mode: '{{ trigger.event.data.params.move_mode }}'
    - if:
      - condition:
        - '{{ mode == "MoveMode.Up" }}'
      then: !input on_button_4_long
  - conditions:
    - '{{ button == 4 and cmd == "move" }}'
    sequence:
    - variables:
        mode: '{{ trigger.event.data.params.move_mode }}'
    - if:
      - condition:
        - '{{ mode == "MoveMode.Down" }}'
      then: !input off_button_4_long
